services:
  - type: web
    name: dina-ecommerce
    env: node
    region: oregon # or choose your preferred region
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # You'll need to set this in Render dashboard
      - key: NEXTAUTH_URL
        sync: false # Will be set automatically by Render
      - key: NEXTAUTH_SECRET
        sync: false # You'll need to set this in Render dashboard
      - key: VERCEL_BLOB_READ_WRITE_TOKEN
        sync: false # For file uploads, set in Render dashboard
      - key: NEXT_PUBLIC_APP_URL
        sync: false # Will be set to your Render service URL
    healthCheckPath: /
    autoDeploy: true
    branch: main # or your default branch

  # Optional: Add a database service if you're using a managed database
  # - type: postgres
  #   name: dina-ecommerce-db
  #   plan: starter
  #   ipAllowList: []
  #   region: oregon # same as web service
  #   disk:
  #     name: postgres-disk
  #     mountPath: /var/lib/postgresql/data
  #     sizeGB: 1 